/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    verifiable: Verifiable;
    submittable: Submittable;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    verifiable: VerifiableSelect<false> | VerifiableSelect<true>;
    submittable: SubmittableSelect<false> | SubmittableSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Warning: Wrong operation could delete production data, please know what you are doing!
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifiable".
 */
export interface Verifiable {
  id: string;
  slug: string;
  verifiable_code: string;
  singleton?: boolean | null;
  max_shared: number;
  depends_on?: string | null;
  depended_by?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  constraints: {
    name: string;
    /**
     * Don't set this to file or payment on required_on_create
     */
    type: 'text' | 'file' | 'payment' | 'boolean' | 'number';
    /**
     * This only affects payment type field
     */
    pay_amount: number;
    /**
     * This also true for text type!
     */
    max_input_size_kb: number;
    mime_type: string[];
    unique?: boolean | null;
    ui_title?: string | null;
    ui_description?: string | null;
    id?: string | null;
  }[];
  required_on_create?:
    | {
        name: string;
        /**
         * Don't set this to file or payment on required_on_create
         */
        type: 'text' | 'file' | 'payment' | 'boolean' | 'number';
        /**
         * This only affects payment type field
         */
        pay_amount: number;
        /**
         * This also true for text type!
         */
        max_input_size_kb: number;
        mime_type: string[];
        unique?: boolean | null;
        ui_title?: string | null;
        ui_description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Warning: Wrong operation could delete production data, please know what you are doing!
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submittable".
 */
export interface Submittable {
  id: string;
  slug: string;
  verifiable: string;
  levels: {
    ui_title?: string | null;
    ui_description?: string | null;
    start_date: string;
    end_date: string;
    constraints: {
      name: string;
      type: 'text' | 'file' | 'payment' | 'boolean' | 'number';
      /**
       * This only affects payment type field
       */
      pay_amount: number;
      /**
       * This also true for text type!
       */
      max_input_size_kb: number;
      mime_type: string[];
      ui_title?: string | null;
      ui_description?: string | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'verifiable';
        value: string | Verifiable;
      } | null)
    | ({
        relationTo: 'submittable';
        value: string | Submittable;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifiable_select".
 */
export interface VerifiableSelect<T extends boolean = true> {
  slug?: T;
  verifiable_code?: T;
  singleton?: T;
  max_shared?: T;
  depends_on?: T;
  depended_by?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  constraints?:
    | T
    | {
        name?: T;
        type?: T;
        pay_amount?: T;
        max_input_size_kb?: T;
        mime_type?: T;
        unique?: T;
        ui_title?: T;
        ui_description?: T;
        id?: T;
      };
  required_on_create?:
    | T
    | {
        name?: T;
        type?: T;
        pay_amount?: T;
        max_input_size_kb?: T;
        mime_type?: T;
        unique?: T;
        ui_title?: T;
        ui_description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submittable_select".
 */
export interface SubmittableSelect<T extends boolean = true> {
  slug?: T;
  verifiable?: T;
  levels?:
    | T
    | {
        ui_title?: T;
        ui_description?: T;
        start_date?: T;
        end_date?: T;
        constraints?:
          | T
          | {
              name?: T;
              type?: T;
              pay_amount?: T;
              max_input_size_kb?: T;
              mime_type?: T;
              ui_title?: T;
              ui_description?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}